### ISSUE TITLE
add parameter generation and password generation for utilizing idrop lite

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#16]
The manual of the iDrop Lite only provides some Jargon code pieces for generating the tightly coupled "password" and "key" parameters for the bulk download mode.  Could the iRODS Consortium add one RESTful service for generating those 2 parameters?

[iROD-Chat:14175] Adding one RESTful service for iDrop Lite

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
