### ISSUE TITLE
 issue with the iRODS REST API "Add Data Object AVU Metadata" method

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#18]
There is an issue with the iRODS REST API "Add Data Object AVU Metadata" method:
1. According to the manual the JSON request body should contain

"objectType":"DATA_OBJECT",
"uniqueNameString":"fedZone1/home/rods/shared"

but shouldn't the "uniqueNameString" contain the name of the data object and not the collection name?
1. After changing the JSON request to contain the data object name using the following request:

curl -X PUT -u <user>:<pass> -H "Accept: application/json" -H "Content-Type: application/json" -d '{"metadataEntries":[{"attribute":"attr1","value":"val1","unit":"unit1","count":1,"lastResult":true,"totalRecords":0}],"objectType":"DATA_OBJECT","uniqueNameString":"testDIRZone/home/rods/testfile2.txt"}' http://dir-vm2.epcc.ed.ac.uk:8080/irods-rest/rest/dataObject/testDIRZone/home/rods/testfile2.txt/metadata

the output is

javax.xml.bind.UnmarshalException
- with linked exception:
  [com.sun.istack.SAXParseException2; columnNumber: 0; unexpected element (uri:"", local:"metadataEntries"). Expected elements are <{http://irods.org/irods-rest}metadataOperation>]

Can you please advise the correct syntax for this method?

**Comment by michael-conway** [comment]
Sure I shall move to GitHub.

I still have an issue with the PUT of collection AVU. When I use the string you have sent me as the request body:

curl -X PUT -u <user>:<pass> -H "Accept: application/json" -H "Content-Type: application/json" -d '{"metadataEntries":[{"attribute":"testBulkAddCollectionAVUJsonAttr1","value":"testBulkAddCollectionAVUJsonValue1","unit":"testBulkAddCollectionAVUJsonUnit1"},{"attribute":"testBulkAddCollectionAVUJsonAttr2","value":"testBulkAddCollectionAVUJsonValue2","unit":"testBulkAddCollectionAVUJsonUnit2"}]}' http://dir-vm2.epcc.ed.ac.uk:8080/irods-rest/rest/collection/testDIRZone/home/rods/metadata

I still get

javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.istack.SAXParseException2; columnNumber: 0; unexpected element (uri:"", local:"metadataEntries"). Expected elements are <{http://irods.org/irods-rest}metadataOperation>]

The testBulkAddCollectionAVUSendJson() should output two strings:

...
System.out.println(body);
...
System.out.println(entityData);
...

**Comment by michael-conway** [comment]
works in CURL test with GitHub HEAD

**Comment by aheyrovsky** [comment]
After re-installing the iRODS REST API it works fine as per the updated documentation. Thanks.

**Comment by michael-conway** [comment]
Awesome!  Thanks for helping improve the library!

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
