### ISSUE TITLE
put to metadata created collection

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#19]
via Justin

I sent the following request to the server.  I was expecting it to create AVU's on /tempZone/home/rods but instead it created the collection /tempZone/home/rods/metadata.  Do you know what I'm doing wrong?  I want to make sure it is not a bug.

```
curl -X PUT -H "ContentType: application/json" -d'{                                                                                      
"metadataEntries":[
{
"attribute":"myattr1",
"value":"myval1",
"unit":"myunit1",
"count":1,
"lastResult":true,
"totalRecords":0
}
],
"objectType":"COLLECTION",
"uniqueNameString":"/tempZone/home/rods"
}' http://rods:rods@localhost:8080/irods-rest/rest/collection/tempZone/home/rods/metadata
```

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
