### ISSUE TITLE
Delete Data Object AVU Metadata - update documentation

### ISSUE THREAD

**Issue by aheyrovsky** [irods-contrib/irods-rest#22]
As per the current documentation the "Delete Data Object AVU Metadata" POST Request Body - JSON seems to be out of date. The following POST Request Body - JSON worked for me:

{"metadataEntries":[{"attribute":"testBulkAddCollectionAVUJsonAttr1","value":"testBulkAddCollectionAVUJsonValue1","unit":"testBulkAddCollectionAVUJsonUnit1"}]}

The documentation needs updating.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
