### ISSUE TITLE
Is there a way to query Resource Information?

### ISSUE THREAD

**Issue by kript** [irods-contrib/irods-rest#24]
Apologies if this is covered anywhere, but I read through the docs and had a look at the source, and can't see any equivalent to the iadmin commands, particularly as pertains to 'lr' and 'leg' or 'ilsresc' for 4.x.

If not, could it be added? I'd offer, but my Java-fu is not strong enough.. :-(

**Comment by michael-conway** [comment]
That's not at all difficult, it's really just a thin JAX-RS wrapper around Jargon.  Do you have a time-frame for this requirement?  You can mark it A-D as a label to help us understand relative priorities.

**Comment by kript** [comment]
My apologies, I can't find a way to add a label to this issue without having some kind of rights to the repo - I'm obviously missing something! For me, its a B on priorities since its no use to the work I need it for without being able to use a number of the iadmin commands that query resources. Time wise before the end of the year would be great, if sooner we may be able to use it as part of our planned upgrade & testing we're getting started on (the road to 4.x!).  Cheers!

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
