### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by mpasserini** [irods-contrib/irods-rest#28]
I would like to do a GET of  the available fileContents in an anonymous way, without any authentication. Is it possible to configure it in this way?

**Comment by mpasserini** [comment]
I managed to download files this way using http://anonymous:anystring@hostname/irods-rest/rest/fileContents/myzone/ not the most beautiful solution but it seems to work

**Comment by mpasserini** [comment]
Is it possible to make anonymous a default user?

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
