### ISSUE TITLE
Read-only REST services (GET and OPTIONS only methods) via filter and config

### ISSUE THREAD

**Issue by mpasserini** [irods-contrib/irods-rest#41]
Hi, Just to make sure... how secure is it to expose the REST API to the web? Is there  a way to prevent brute force on the accounts?
Is there a way to limit the requests to only GET requests? Is it enough to comment out the following fields in /opt/irods-rest/src/main/resources/jargon-beans.xml ?

```
                    <util:list id="methodsList" value-type="java.lang.String">
                            <beans:value>GET</beans:value>
            <!--            <beans:value>POST</beans:value>
                            <beans:value>DELETE</beans:value>
                            <beans:value>PUT</beans:value> -->
                    </util:list>
```

**Comment by michael-conway** [comment]
The REST API is secure in the sense that it runs completely separate from iRODS, and no connection to iRODS directly is exposed to the network.  The iRODS security model is in effect and all access is through iRODS authentication and authorization.  It runs in a Java sandbox and goes to the iRODS protocol, so no direct execution of any irods code takes place in the mid-tier.

DOS detection and firewalls are external to the REST API, it's a web app like any other typical application, it can be clustered, etc. This is a stateless, share-nothing design.  Basic Auth is used, and the REST service is locked down to a specific target iRODS grid through deployment configuration.

I think your idea of having a 'read only' version of the REST API is fairly straight-forward by adding a servlet filter.  This would only allow OPTION and GET requests.  That does not exist currently, it would be a new feature.  The config you refer to above is specifically for setting CORS headers, and does not provide this functionality.

**Comment by mpasserini** [comment]
Ok thank you for the reply!

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
