### ISSUE TITLE
Ticket creation doesn't accept JSON request body

### ISSUE THREAD

**Issue by muhrin** [irods-contrib/irods-rest#46]
This works fine:

`curl -H 'Accept: application/xml' -H 'Content-Type: application/xml' --data '<ns2:ticket xmlns:ns2="http://irods.org/irods-rest"><mode>read</mode><object_path>[SOME FILE]</object_path></ns2:ticket>' http://***:8080/irods-rest/rest/ticket`

But the JSON equivalent fails:

`curl -H 'Accept: application/xml' -H 'Content-Type: application/json' --data '{"mode": "read", "object_path": "[SOME FILE]"}' http://***:8080/irods-rest/rest/ticket
javax.xml.bind.UnmarshalException`
with error:
`with linked exception:
[com.sun.istack.SAXParseException2; columnNumber: 0; unexpected element (uri:"", local:"mode"). Expected elements are <{http://irods.org/irods-rest}ticket>]`

The code has ignored the ContentType declaration and appears to be following the same codepath as if XML were specified (judging by the XML parser exception).

I haven't checked any of the other REST commands - perhaps they have the same problem.

**Comment by JustinKyleJames** [comment]
Can you send the exact request.  When I ran a similar request it worked.

```
$ curl -H 'Accept: application/xml' -H 'Content-Type: application/json' --data '{"mode": "read", "object_path": "/tempZone/home/rods"}' http://rods:rods@localhost:8080/irods-rest/rest/ticket

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:ticket xmlns:ns2="http://irods.org/irods-rest"><ticket_string>kfN3hOUjiQ5lCBR</ticket_string></ns2:ticket>
```

**Comment by muhrin** [comment]
Thanks for the quick reply Justin.

Hmm, interesting.  Here's the full request (sans password):

`curl -s --user muhrin:[pass] -H 'Accept: application/xml' -H 'Content-Type: application/json' --data '{"mode": "read","object_path": "/cscs/home/muhrin/1k.dat"}' http://sobrio.cscs.ch:8080/irods-rest/rest/ticket`

iRODS version 4.2.0.

**Comment by JustinKyleJames** [comment]
Could you try that on a 4.1.x version of iRODS?  I can't imagine 4.2 would cause such a problem but since it isn't a tested version yet I'd like to see if you still have your issue on 4.1.x.

I'm also curious if you happen to have some special character in your request.  Might be worth typing that in manually for a second try.

**Comment by michael-conway** [comment]
I'll take a look this has to do with the vagaries of the namespace mapping with the JSON binding libraries.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
