### ISSUE TITLE
ticket errors - anonymous not being supported

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#49]
expire time: none

data-object name: irods-icommands-4.1.6-64bit.tar.gz

data collection: /path/to/file

No host restrictions

No user restrictions

No group restrictions

anonymous access is set up on the iRODS server and I can get the file, provided I use the anonymous username, with an iget -t JJz9fIjXEvN0rMz

However if I try via the rest interface then it does not work, unless I use a real username and password. So if I user the URL

https://servername/irods-rest/rest/fileContents/path/to/file/irods-icommands-4.1.6-64bit.tar.gz?ticket=JJz9fIjXEvN0rMz

and enter real credentials then I get the file, but if I use anonymous credentials (a random string as password seems to be required), then I get "The requested resource () is not available."

The tomcat logs imply that auth went OK, but that it can't see the file:

---

2752272 [http-8080-4] INFO  org.irods.jargon.rest.commands.collection.CollectionService  - collectionData:org.irods.jargon.rest.domain.CollectionData@5927ec

2752272 [http-8080-4] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - filter(requestContext,responseContext

2752272 [http-8080-4] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - restConfiguration:RestConfiguration [irodsHost=irodshost, irodsPort=1247, irodsZone=tempZone, defaultStorageResource=wos, realm=irods-rest, utilizePackingStreams=true, authType=PAM, allowCors=true, corsOrigins=[*], corsMethods=[GET, POST, DELETE, PUT], corsAllowCredentials=true, corsAllowedHeaders=[x-requested-with, x-requested-by], webInterfaceURL=]

2752272 [http-8080-4] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - cors allowed

2752272 [http-8080-4] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - no origin, not options, or cords.failure is set..ignore

2752272 [http-8080-4] WARN  org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore

2837113 [http-8080-4] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - doFilter()

2837113 [http-8080-4] ERROR org.irods.jargon.rest.auth.BasicAuthFilter  - auth null or empty

2843590 [http-8080-3] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - doFilter()

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - getIRODSAccountFromBasicAuthValues

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - credentials:anonymous

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - restConfiguration:RestConfiguration [irodsHost=irodshost, irodsPort=1247, irodsZone=tempZone, defaultStorageResource=wos, realm=irods-rest, utilizePackingStreams=true, authType=PAM, allowCors=true, corsOrigins=[*], corsMethods=[GET, POST, DELETE, PUT], corsAllowCredentials=true, corsAllowedHeaders=[x-requested-with, x-requested-by], webInterfaceURL=]

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - using PAM

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - see if auth scheme is overrideen by the provided credentials

2843591 [http-8080-3] DEBUG org.irods.jargon.rest.auth.RestAuthUtils  - userId:anonymous

2843591 [http-8080-3] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - irods account for auth:irods://anonymous@irodshost:1247

2843591 [http-8080-3] WARN  org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore

2843685 [http-8080-3] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - authResponse:org.irods.jargon.core.connection.auth.AuthResponse@af624a0

2843685 [http-8080-3] INFO  org.irods.jargon.rest.auth.BasicAuthFilter  - success!

2843686 [http-8080-3] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - filter(requestContext)

2843686 [http-8080-3] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - restConfiguration:RestConfiguration [irodsHost=irodshost, irodsPort=1247, irodsZone=tempZone, defaultStorageResource=wos, realm=irods-rest, utilizePackingStreams=true, authType=PAM, allowCors=true, corsOrigins=[*], corsMethods=[GET, POST, DELETE, PUT], corsAllowCredentials=true, corsAllowedHeaders=[x-requested-with, x-requested-by], webInterfaceURL=]

2843686 [http-8080-3] DEBUG org.irods.jargon.rest.auth.IrodsCorsFilter  - no origin in header, ignore

2843686 [http-8080-3] INFO  org.irods.jargon.rest.commands.dataobject.FileContentsService  - getFile()

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - getIRODSAccountFromBasicAuthValues

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - index of end of basic prefix:5

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - credentials:anonymous

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - restConfiguration:RestConfiguration [irodsHost=irodshost, irodsPort=1247, irodsZone=tempZone, defaultStorageResource=wos, realm=irods-rest, utilizePackingStreams=true, authType=PAM, allowCors=true, corsOrigins=[*], corsMethods=[GET, POST, DELETE, PUT], corsAllowCredentials=true, corsAllowedHeaders=[x-requested-with, x-requested-by], webInterfaceURL=]

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - using PAM

2843686 [http-8080-3] INFO  org.irods.jargon.rest.auth.RestAuthUtils  - see if auth scheme is overrideen by the provided credentials

2843686 [http-8080-3] DEBUG org.irods.jargon.rest.auth.RestAuthUtils  - userId:anonymous

2843686 [http-8080-3] INFO  org.irods.jargon.rest.commands.dataobject.FileContentsService  - decoded path:/path/to/file//Bob/irods-icommands-4.1.6-64bit.tar.gz

2843701 [http-8080-3] INFO  org.irods.jargon.rest.commands.dataobject.FileContentsService  - file does not exist

2843701 [http-8080-3] WARN  org.jboss.resteasy.core.ExceptionHandler  - failed to execute

javax.ws.rs.WebApplicationException: HTTP 404 Not Found

---

**Comment by bobfcregan** [comment]
It looks like this is not a REST bug, but actually an iRODS bug. See   https://github.com/irods/irods/issues/3139

The REST download works fine when there is a cache copy available, and fails when there is not.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
