### ISSUE TITLE
Feature request: SE4 Implementation

### ISSUE THREAD

**Issue by kript** [irods-contrib/irods-rest#59]
The additions to a REST API defined here; https://github.com/beamly/SE4/blob/master/SE4.md would be helpful if we could have a similar setup that allowed service level monitoring of the service without requiring a login.

Its a nice to have, I fully admit that.. :-)

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
