### ISSUE TITLE
issue on upload with unsupported media type - [iROD-Chat:16451] 

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#63]
We recently deployed the most recent iRODS REST API, and all the functions are working fine except for uploads. Upload requests always generate a 415 Unsupported Media Type error, and the Tomcat logs give me this:
javax.ws.rs.NotSupportedException: Cannot consume content type

Here's an example of how I'm trying to test this, which appears to me to conform to the API documentation:
curl -v -n --basic -X POST --data-binary uploadFile=@test.file https://web.example.com/irods-rest/rest/fileContents/collectionName/test.file
I've tried numerous variations of the --data options, and I've also tried adding a content-type specification at the command-line, with no change in the behavior. Am I missing something obvious WRT how my requests should be formed or how the server should be configured? Has anyone else seen this behavior? The tomcat server is sitting behind an SSL-enabled web proxy server which otherwise works for everything else I've tested with.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
