### ISSUE TITLE
rest issue with namespace

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#64]
json response

**Comment by PaulVanSchayck** [comment]
After latest commit I'm getting

```
{
    "metadataListing": {
        "@objectType": "COLLECTION",
        "metadataEntries": [
            {
                "@count": "1",
                "@lastResult": "true",
                "@totalRecords": "0",
                "attribute": "ingestResource",
                "unit": "",
                "value": "iresResource"
            },
            {
                "@count": "2",
                "@lastResult": "true",
                "@totalRecords": "0",
                "attribute": "resource",
                "unit": "",
                "value": "replRescAZM01"
            },
            {
                "@count": "3",
                "@lastResult": "true",
                "@totalRecords": "0",
                "attribute": "title",
                "unit": "",
                "value": "Don't you wish you had more energy... or less ambition?"
            }
        ],
        "uniqueNameString": "nlmumc/projects/P000000010"
    }
}
```

**Comment by michael-conway** [comment]
Yes, it appears to be about picking up a json library, and it does not
exhibit that behavior in the unit tests, so it may be a json 'driver'
priority issue when packaged.  that's my thinking.

**Comment by michael-conway** [comment]
try that last commit as a test, it's fixed in the docker image from here
now....I'm curious...

**Comment by PaulVanSchayck** [comment]
Confirmed! This fixes the problem for JSON. But it indeed breaks the XML output.

**Comment by michael-conway** [comment]
Yes I might address in 2 phases...but that was a test

**Comment by PaulVanSchayck** [comment]
Hi Mike,

Hope you had a good trip back to the US. It was good to meet you at the UGM. 

Did you have time to further look into this issue? We are considering to use this XML breaking version as we do not use the XML output. But a fully fixed version is always nicer.

Thanks,

Paul

**Comment by michael-conway** [comment]
Yes let's look at this this week.  I'm happy to update the version so you
guys can get things done and that would give time to find a final
resolution.  As I stated at UGM we're moving from JBoss RestEasy to the
more simple Spring 4 via Swagger.  I found other cases where RestEasy was
overly complicated and difficult to merge with Spring, notably for Spring
Security.

Let's try and hit this perhaps Thursday or Friday?

**Comment by PaulVanSchayck** [comment]
We're okay with using the current commit. It's no problem for us to build a custom war and integrate that into our deployment.

I understand fixing this properly takes time away from making the move to the Spring4/Swagger implementation. It's up to you to determine how important it is to get this 4.1.10.0-RC1 to a stable release, before the Swagger implementation is there.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
