### ISSUE TITLE
Update for 4.3 release train

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#67]
Update for 4.3

**Comment by michael-conway** [comment]
Hey @jasoncoposky and @trel please feel free to pass this issue regarding a deployable .war file. I'll look at this this week and plan on a release that tracks the 4.3 release.

I expect we'll be moving to a new Swagger based API soon, but this can serve as an interim solution.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
