### ISSUE TITLE
issue posting metada updates

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#69]
URL: http://xxxxxxxxx/irods-rest/rest/collectionxxxx_ZONE/home/xx/xxxxxx/metadata
Body: {"metadataEntries":[{"attribute":"testBulkAddCollectionAVUJsonAttr1","value":"testBulkAddCollectionAVUJsonValue1","unit":"testBulkAddCollectionAVUJsonUnit1"},{"attribute":"testBulkAddCollectionAVUJsonAttr2","value":"testBulkAddCollectionAVUJsonValue2","unit":"testBulkAddCollectionAVUJsonUnit2"}]}
Headers: accept: application/json, Content-Type: application/json
 
Note: the JSON is copied directly from the iRODS documentation (file:///Users/xxxxxxxx/Downloads/iRODSRESTAPIDocumentation.pdf).
 
I should get back a JSON response with the status for each metadata entry, but instead I get this error:
javax.xml.bind.UnmarshalException
- with linked exception:
[com.sun.istack.SAXParseException2; columnNumber: 0; unexpected element (uri:"", local:"metadataEntries"). Expected elements are <{}metadataEntry>,<{}metadataOperation>]
 
When I search for this error I see Github entries from 2015 saying this is fixed (https://github.com/DICE-UNC/irods-rest/issues/18 and https://github.com/DICE-UNC/irods-rest/issues/21).

**Comment by michael-conway** [comment]
Seems to work now...will update docker image and push

![image](https://user-images.githubusercontent.com/1097261/44103406-27e681e0-9fba-11e8-8d58-f8a4765b018e.png)

**Comment by michael-conway** [comment]
committed to master and pushed as  docker push diceunc/rest:4.3.0.1-RC1

Pls test and advise!

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
