### ISSUE TITLE
Switch to swagger api

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/irods-rest#70]
new rev based on swagger2

**Comment by michael-conway** [comment]
good notes https://restfulapi.net/rest-api-design-tutorial-with-example/

**Comment by michael-conway** [comment]
swagger hub: https://app.swaggerhub.com/apis/michael-conway/IRODS-REST/1.0.0 (provisional)

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
