### ISSUE TITLE
Use of auth plugins such as openid

### ISSUE THREAD

**Issue by RubenGarcia** [irods-contrib/irods-rest#72]
We are trying to use openid to authentificate with irods, using the plugin at 
https://github.com/irods-contrib/irods_auth_plugin_openid

However, there is no mention of plugins in irods-rest. Can you confirm if there are plans to get openid working (something similar to https://github.com/irods/python-irodsclient/issues/130)?

**Comment by michael-conway** [comment]
My understanding with @Terrell Russell <tgr@renci.org> is that iRODS server
is planning on implementing this through the PAM plugin. Given that it
should be rather straightforward.

NB there is a new Swagger Based REST API in development on my part that
will end up superseding this API and will probably be the focus of extended
development. Not to say we couldn't get OpenID into here, but at some point
we should move forward.

**Comment by trel** [comment]
Correct - the PAM investigation is being led by our friends at Maastricht.

**Comment by RubenGarcia** [comment]
Is there an (approximate) timeline for when this new PAM+openid concept would be ready to use by final users?

**Comment by RubenGarcia** [comment]
Regarding your Swagger Based REST API, do you have an (approximate) timeline for when this would be considered stable and ready to use by final users?

Thank you.

**Comment by michael-conway** [comment]
My goal would be to have an initial by the December timeframe with
'essentials'. The initial version is being utilized for file streaming and
JWT token management for a demo of an iRODS GA4GH Data Repository Service
API at their Plenary...

What we really need are collaborators, both at the API definition level and
the implementation level. I'm already talking with @Jason Coposky
<jasonc@renci.org> on this front.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
