### ISSUE TITLE
4.3.1.0-RELEASE not available in maven 404

### ISSUE THREAD

**Issue by kavanLi** [irods-contrib/irods-rest#75]
https://raw.github.com/DICE-UNC/DICE-Maven/master/releases response 404 : not found
So, I can not use maven version 2.2.1 to package irods-rest. Always failure.

<dependency>
            <groupId>org.irods.jargon</groupId>
            <artifactId>jargon-core</artifactId>
            <version>4.3.1.0-RELEASE</version>
</dependency>
please help.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
