### ISSUE TITLE
Is this discontinued?

### ISSUE THREAD

**Issue by darwinjob** [irods-contrib/irods-rest#76]
If yes, what should I do if I need iRODS REST API?

**Comment by trel** [comment]
No, we're still here.   This API still works.

There is also a new C++ REST API under development at https://github.com/irods/irods_client_rest_cpp - no releases yet.

**Comment by michael-conway** [comment]
If there was enough community support I'd jump in and update this

**Comment by trel** [comment]
@darwinjob is there anything in particular you're needing?

**Comment by michael-conway** [comment]
I think a few things to ponder:


   - What's the state of the C version? I'm not going to work on the C code
   but would be happy to contribute to the OpenAPI side of things. If this was
   ready to roll the point is moot
   - What do we feel about the existing OpenAPI spec? Is it viable and
   represents a good consensus? Is it implemented as spec'd or partially
   implemented?
   - If we get to this point I'd be willing to work on updating it but
   would love to have help. For myself I would still do it in Java as python
   still doesn't have a lot of things, I'm hoping to eventually jump on Go as
   a second client library of interest...really that's just personal
   preference. I'd like to reuse libraries at any rate so I could back Metalnx
   in the shift to REST through the shortest route.

   I don't know what folks think, I'm also happy to just be a consumer if
   there's sufficient effort on this ;-)

**Comment by darwinjob** [comment]
> @darwinjob is there anything in particular you're needing?

Well, I need REST for my data :)

Here is the story. More than 10 years ago we developed a data management system for our in-lab needs (mainly high resolution microscopy images - storing/sharing/viewing online). For now we have accumulated around 100T of the image data (TIFFs, DeepZoom pyramids, SVGs, NIfTIs) and metadata. Unfortunately the technologies we've been using are discontinued so we have to migrate. Fortunately iRODS seems like a perfect match as the replacement (plus extras). However, our web viewers require HTTP access to the data and I think this is where iRODS REST should kick in. Example:
https://wiki.uio.no/projects/navigator3/index.php/Tg-Arc-Swe_Atlas

There're two use cases presented on the page: 1) view the images http://cmbn-navigator.uio.no/navigator/filmstrip/index.html?blockId=381 and 2) download the images http://cmbn-navigator.uio.no/navigator/feeder/all_originals/?id=381
I believe both should be possible to implement using iRODS REST.

Our main concern is the updates - the latest one is 2 years old. Are you planning to continue developing this or we should look for something else (like REST2)?

Best regards
ДД

**Comment by michael-conway** [comment]
REST2 was a false start to pick up on OpenAPI, however the consortium had
jumped in with a REST API so that got put on the back burner, so really to
me this is a question of whether to fire that up again, I was not trying to
duplicate efforts ;-)

MC

**Comment by darwinjob** [comment]
OK, thanks for the explanations.
So if I need iRODS REST now I should use this project? There are no alternatives?

**Comment by michael-conway** [comment]
Sure, it's just an older framework (a wayback version of JBoss RestEasy).
I'm willing to fire up a new version based on a more modern framework. It
looked like the Consortium was going a different direction and I wasn't
quite sure what to do there. I'd probably start with that REST2 project,
tear it back down, and start again building up around an OpenAPI SPEC. I'm
just trying to get a feel for whether that's duplicative, I'm not
interested in setting up a competing API, etc but it is an important thing,
I agree.

Like I said my main languages are Java, and increasingly Go and I plan on
sticking to those environments. It'd be great if there were other devs to
jump in b/c I can only do best effort and really it's on my own time at
this point.

**Comment by trel** [comment]
Archiving this repository.

Please find the new HTTP API implementation at:

https://github.com/irods/irods_client_http_api
